name: Install and Load

on:
  push:

jobs:
  install_and_load:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}
    - name: download test files
      shell: bash -l {0}
      run: |
         wget -P fastq/ https://github.com/nf-core/test-datasets/raw/rnaseq/testdata/GSE110004/SRR6357070_1.fastq.gz -O fastq/test1_S1_R1_L001.fastq.gz
         wget -P fastq/ https://github.com/nf-core/test-datasets/raw/rnaseq/testdata/GSE110004/SRR6357071_1.fastq.gz -O fastq/test2_S2_R1_L001.fastq.gz
         wget https://github.com/LouisFaure/bulktools-py/raw/main/test/genes.gtf.gz
         wget https://github.com/LouisFaure/bulktools-py/raw/main/test/star_test.tar.gz && tar xvf star_test.tar.gz
    - name: Install dependencies
      shell: bash -l {0}
      run: conda install -c bioconda star subread
    - name: Install package
      shell: bash -l {0}
      run: pip install . && bt -h
    - name: Run bt
      shell: bash -l {0}
      run: bt --star_ref star_test --gtf genes.gtf.gz && python -c "import anndata;print(anndata.read_h5ad('adata_bulk_star.h5ad'))"
