name: Install and Test

on:
  push:

jobs:
  install_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}
    - name: download test files
      shell: bash -l {0}
      run: |
         wget https://github.com/LouisFaure/bulktools-py/raw/main/test/fastq.tar && tar xvf fastq.tar
         wget https://github.com/LouisFaure/bulktools-py/raw/main/test/genes.gtf.gz
         wget https://github.com/LouisFaure/bulktools-py/raw/main/test/star_test.tar.gz && tar xvf star_test.tar.gz
         wget https://github.com/LouisFaure/bulktools-py/raw/main/test/assert.py
    - name: Install dependencies
      shell: bash -l {0}
      run: conda install -c bioconda star subread
    - name: Install package
      shell: bash -l {0}
      run: pip install . && bt -h && ls
    - name: Run bt
      shell: bash -l {0}
      run: bt --star_ref star_test --gtf genes.gtf.gz && python assert.py
